version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package/

  build:
    commands:
      - echo "Packaging Lambda function..."
      - cp lambda_functions.py package/   # <-- ensure filename matches your repo
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..

  post_build:
    commands:
      - echo "Checking AWS credentials..."
      - aws sts get-caller-identity
      - echo "Listing objects in S3 bucket..."
      - aws s3 ls s3://lambdas-buildss-zip/
      - echo "Listing Lambda functions..."
      - aws lambda list-functions --region ap-south-1
      - echo "Uploading deployment package to S3..."
      - aws s3 cp deployment_package.zip s3://lambdas-buildss-zip/ --region ap-south-1
      - echo "Updating Lambda function..."
      - echo "Deployment complete!"
