version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t package/

  build:
    commands:
      - echo "Packaging Lambda function..."
      - cp lambda_functions.py package/
      - cd package
      - zip -r ../deployment_package.zip .
      - cd ..

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp deployment_package.zip s3://lambdas-buildss-zip/
      - echo "Updating Lambda function..."
      - aws lambda update-function-code \
          --function-name github-to-lambda-cicd \
          --s3-bucket lambdas-buildss-zip \
          --s3-key deployment_package.zip
      - echo "Deployment complete!"
