name: Deploy Lambda

on:
  push:
    branches:
      - main  # deploys on every push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: Global  # replace with your AWS region

      - name: Package Lambda function
        run: zip -r function.zip .

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name myLambda \
            --zip-file fileb://function.zip
